### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by CarineGottschall** [Horea94/Fruit-Images-Dataset#1]
Hi,
I tried running your network on my raspberry pi 3 and in the code build_image_data.py, I received the following error message:
Traceback (most recent call last):
File "build_image_data.py", line 405, in <module>
tf.app.run()

And looking in the other codes, I didn't find the definition of the run function of the tensorflow. Can you help me, please?

Thank you very much in advance.

**Comment by CarineGottschall** [comment]
Unfortunally not, could you tell me what are the libraries versions that you used in these codes?

**Comment by CarineGottschall** [comment]
I have tried to send you the error message but I don't get by here. Could you give me your email?

**Comment by Horea94** [comment]
My email is horea94@gmail.com

The libraries used are 
TensorFlow r1.7
Numpy 1.14

Using python 3.6
