### ISSUE TITLE
same problem in run

### ISSUE THREAD

**Issue by mohammad69h94** [Horea94/Fruit-Images-Dataset#12]
Hi. when i run and test program using this command :
my OS is windows 7.

C:\Users\ali\Downloads\Compressed\frt\src\image_classification>python fruit_dete
ction.py --image_path=images/cherryWaxYellow.jpg

 occure this error:

[[Node: ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0 /task:0/device:CPU:0"](WholeFileReaderV2, input_producer_1)]]

**Comment by Horea94** [comment]
This error message seems to indicate that the path to the jpg file "images/cherryWaxYellow.jpg" does not exist.

Please make sure you are providing the correct path to the file you want to run the detection on.

**Comment by mohammad69h94** [comment]
> This error message seems to indicate that the path to the jpg file "images/cherryWaxYellow.jpg" does not exist.
> 
> Please make sure you are providing the correct path to the file you want to run the detection on.

dfffg

**Comment by mohammad69h94** [comment]
> This error message seems to indicate that the path to the jpg file "images/cherryWaxYellow.jpg" does not exist.
> 
> Please make sure you are providing the correct path to the file you want to run the detection on.

I'm sure the path is right. But again occure same error:
C:\Users\ali\Downloads\Compressed\frt\src\image_classification\fruit_detection>p
ython fruit_detection.py --image_path images/apple.jpg

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_3_input_pro
ducer_1' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0
/task:0/device:CPU:0"](WholeFileReaderV2, input_producer_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fruit_detection.py", line 76, in <module>
    process_image(sess, X, softmax, keep_prob, image, height, width, depth)
  File "fruit_detection.py", line 42, in process_image
    image_height = sess.run(image_height)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 900, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1316, in _do_run
    run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_3_input_pro
ducer_1' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0
/task:0/device:CPU:0"](WholeFileReaderV2, input_producer_1)]]

Caused by op 'ReaderReadV2_1', defined at:
  File "fruit_detection.py", line 73, in <module>
    image, height, width, depth = read_image(image_path, image_reader)
  File "fruit_detection.py", line 16, in read_image
    _, image_file = image_reader.read(filename_queue)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\io_ops
.py", line 164, in read
    return gen_io_ops.reader_read_v2(self._reader_ref, queue_ref, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_io
_ops.py", line 977, in reader_read_v2
    queue_handle=queue_handle, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-
access

OutOfRangeError (see above for traceback): FIFOQueue '_3_input_producer_1' is cl
osed and has insufficient elements (requested 1, current size 0)
         [[Node: ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0
/task:0/device:CPU:0"](WholeFileReaderV2, input_producer_1)]]

**Comment by Horea94** [comment]
You omitted an = sign in the command line.
This is how you should run it the file:
python fruit_detection.py --image_path=images/apple.jpg

Also make sure the target image (images/apple.jpg in this case) isn't opened in another process.

**Comment by mohammad69h94** [comment]
> You omitted an = sign in the command line.
> This is how you should run it the file:
> python fruit_detection.py --image_path=images/apple.jpg
> 
> Also make sure the target image (images/apple.jpg in this case) isn't opened in another process.
i correct this. but occure same error.
I do not have a powerful system to training dataset of fruits for detection. for this reason i got your training files from you. This may be due to this error?

**Comment by Horea94** [comment]
I tested the same files I sent you with tensorflow 1.9 and I did not get any errors.
I am not sure what is the cause of your problem.

**Comment by mohammad69h94** [comment]
> I tested the same files I sent you with tensorflow 1.9 and I did not get any errors.
> I am not sure what is the cause of your problem.

very well. thank you so much. i hope to solve it)

**Comment by mohammad69h94** [comment]
> I tested the same files I sent you with tensorflow 1.9 and I did not get any errors.
> I am not sure what is the cause of your problem.

when i train myself for the short time, it Works fine! it detect image but low probability.
