### ISSUE TITLE
problem in test

### ISSUE THREAD

**Issue by mohammad69h94** [Horea94/Fruit-Images-Dataset#13]
Hi, I succeeded train network for 40,000 repetitions :
.
.
.
time: 57 step: 39500 loss: 0.0116 accuracy: 1.0000
time: 60 step: 39750 loss: 0.0094 accuracy: 1.0000
time: 61 step: 40000 loss: 0.0010 accuracy: 1.0000

 but in the level of test and predict. i get this result:

Predicted 367 out of 400; partial accuracy 0.8950
Predicted 465 out of 500; partial accuracy 0.9009
Predicted 560 out of 600; partial accuracy 0.9019
Predicted 648 out of 700; partial accuracy 0.8961
final accuracy on test data : 0.8942356
{'Apple Breaburn': 65, 'Apple Golden 1': 9, apple golden 2': 10, .........'banana': 30, banana lady finger : 8.....
 what is mean?

and the level of prediction i get this result:
python detect_fruits.py --image_path=images/redapple.jpg
label index: 18 - label: cactus fruit - probability: 0.7114

**Comment by Horea94** [comment]
The output of the test file includes a map that contains entries of type "label" : "number" where label is a fruit class name, an the number represents how many test images from that label were classified incorrectly. This is to show which fruit classes are more difficult to classify.
For example, in your case 'banana': 30 means that 30 images with bananas were classified as something else.

When using the detection script, bear in mind that it is only a basic example that takes an image, resizes it to 100 x 100 pixels and runs it through the network. 
Also, if the images you are trying to use in detection are very different from the training ones (for example there is a lot of light, or very little light, or the background of the image is not white) then the network won't predict them properly.

**Comment by mohammad69h94** [comment]
thanks so much
