### ISSUE TITLE
how to feed network with custom image?

### ISSUE THREAD

**Issue by rexludus** [Horea94/Fruit-Images-Dataset#21]
hello, i've got the same issue like mentioned here: https://github.com/Horea94/Fruit-Images-Dataset/issues/7 . how can I feed the network with my own captured image and see the returned result?

**Comment by Horea94** [comment]
If you have an image with one fruit, you can resize the image to 100 x 100 pixels and then feed it in the network as per the example in [detect_fruits.py](https://github.com/Horea94/Fruit-Images-Dataset/blob/master/src/image_classification/fruit_detection/detect_fruits.py) for TensorFlow.
For Keras, you can see the test_generator in [Fruits-360 CNN.ipynb](https://github.com/Horea94/Fruit-Images-Dataset/blob/master/src/image_classification_keras/Fruits-360%20CNN.ipynb), which can load all the images from a folder and feed them in a network.

If you have an image with multiple fruits, you need a segmentation algorithm to break the image into sub-images that contain only one fruit and then pass them through this model.

**Comment by rexludus** [comment]
thank you very much!
