### ISSUE TITLE
how to get the label

### ISSUE THREAD

**Issue by z0v0z** [Horea94/Fruit-Images-Dataset#26]
Hello!

I see that there are only images in the train folder, but no labels. How can I get the label. txt corresponding to the images in the train folder? I would greatly appreciate it if you could help me solve this problem.

**Comment by Horea94** [comment]
Hello,

The label of the images is the folder name. So if you have, for example, the file Train/Apple Golden/100.jpg, the label associated with the 100.jpg file is Apple Golden.
