### ISSUE TITLE
extract_images documentation

### ISSUE THREAD

**Issue by CJRobey** [Horea94/Fruit-Images-Dataset#5]
I am currently trying to use the extract_images.cpp file for a different application (figurine model dogs) and it is fairly unclear what the arguments are doing in the r_box struct and how the code works as a whole. 

Can there be some more documentation on how this file operates? In my opinion it could be extremely useful for generic industry use, but right now it is very unclear.

**Comment by mihaioltean** [comment]
t_box is type for defining a rectangular bounding box . Corners of the box are stored in min and max data members.

Now I have added more comments in the source code. Please tell me which part you do not understand.

Please note that the background should note have too many fluctuations. In our case we have placed a white sheet of paper behind the fruits. Still, white paper does not mean white background on movie (mainly due shadows). If your background is very varied you need some more complex algorithms ... check for the image segmentation problem.

**Comment by CJRobey** [comment]
![image_screenshot_12 06 2018](https://user-images.githubusercontent.com/15220989/41307536-142a1d80-6e3f-11e8-810f-23dfa2795bdb.png)

I don't know how to increase the size of the box though. Whenever I try to do that, I either get an error from OpenCV or the dimensions become very strange.

How should I edit the line in fruits_definition.h to increase this parameter properly?

Rect r_box(705, 205, 205, 205);

**Comment by mihaioltean** [comment]
send me the full image.

**Comment by CJRobey** [comment]
![cocker_spaniel_364](https://user-images.githubusercontent.com/15220989/41310042-f9db399e-6e45-11e8-965e-3e548f0fd6c4.png)

**Comment by CJRobey** [comment]
What r_box parameters did you use for that image?

**Comment by mihaioltean** [comment]
Rect r_box(390, 180, 540, 540);
#define motor_shaft_height 1
#define color_distance 3

However, some changes are required in the main function because the program is intended to work with movies not with images.

Also, update to the latest version because I fixed a problem: I worked with "smaller_image_size" constant (which was defined as 100) but somewhere in the program I used value 100 ... maybe this is why you got crash if you changed the smaller_image_size.
