### ISSUE TITLE
How to use folder test-multiple_fruits for code ?

### ISSUE THREAD

**Issue by MrK-0day** [Horea94/Fruit-Images-Dataset#7]
Hello, i want use your code for detection apple in images, but i do not know how to use it. i finished train the network. Please help me ?

**Comment by mihaioltean** [comment]
Hi,

You could take any square from an image, scale it (up or down) to 100x100 pixels and send it to the network.

regards,

**Comment by MrK-0day** [comment]
Hi, thank you so much, I'm a beginner student. Can you give me specific instructions on how to do it? Thanks so much if you can help me that.

**Comment by mihaioltean** [comment]
Hi,

If you use OpenCV to read images from disk you can use the following instruction:

cv::Mat B = A( cv::Rect( left, top, width, height ) );

to extract a subimage from an image. Then you can save it to file and send it to the network.

Note that left, top, width, height variables must take any valid values inside the image.

regards,

**Comment by MrK-0day** [comment]
I don't know. how to send it to the network ? please help me, because i am noob in tensorflow.

**Comment by Horea94** [comment]
I will add a new script later today with a commented example on how to read and feed an image to a trained tensorflow model.
I will notify you when I upload the script.

**Comment by MrK-0day** [comment]
oh, thanks so much, i love u

**Comment by Horea94** [comment]
I added the script.
Please check it and let me know if you have any issues.

**Comment by MrK-0day** [comment]
Hi, i have one issues, i need you help me.
![image](https://user-images.githubusercontent.com/33540741/41924905-5f6e2fc8-7995-11e8-98bb-5b2d222bb001.png)

**Comment by MrK-0day** [comment]
oh sorry, i see it. Can you help me partition the picture so I'm needing it in learning ? It's like that.
![image](https://user-images.githubusercontent.com/33540741/41925231-3196166e-7996-11e8-8c48-4af543ca51ee.png)

**Comment by Horea94** [comment]
Currently we do not have such logic in our code, however I recommend you take a look over the TensorFlow documentation here:
https://www.tensorflow.org/versions/master/api_docs/python/tf/extract_image_patches
From what I know, this function does what you need.

**Comment by MrK-0day** [comment]
Thank you very much for your help.
