### ISSUE TITLE
Partial accuracy 0.000???

### ISSUE THREAD

**Issue by sainisanjay** [Horea94/Fruit-Images-Dataset#8]
Hello @Horea94 
I have used `useCkpt = False` during training and it gave me error during testing as per below.
```
File "network/fruit_test_net.py", line 82, in <module>
    saver.restore(sess, ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
```
In order to resolve above issue i commented `#saver.restore(sess, ckpt.model_checkpoint_path)` in the `fruit_test_net.py` test script. After that it runs well but it gave me Partial accuracy 0.000.
````
Predicted 5 out of 100; partial accuracy 0.0000
Predicted 8 out of 200; partial accuracy 0.0000
Predicted 9 out of 300; partial accuracy 0.0000
Predicted 10 out of 400; partial accuracy 0.0000
Predicted 12 out of 500; partial accuracy 0.0000
Predicted 13 out of 600; partial accuracy 0.0000
Predicted 16 out of 700; partial accuracy 0.0000
Predicted 19 out of 800; partial accuracy 0.0000
Predicted 20 out of 900; partial accuracy 0.0000
Predicted 23 out of 1000; partial accuracy 0.0000
Predicted 27 out of 1100; partial accuracy 0.0000
Predicted 28 out of 1200; partial accuracy 0.0000
Predicted 32 out of 1300; partial accuracy 0.0000
Predicted 34 out of 1400; partial accuracy 0.0000
Predicted 38 out of 1500; partial accuracy 0.0000
```
any idea??

**Comment by Horea94** [comment]
The commented line #saver.restore(sess, ckpt.model_checkpoint_path) is responsible for loading the saved model . Without it , the script does not load anything and tests a model that was not trained, so the result is 0% accuracy.

**Comment by Horea94** [comment]
It seems that the ckpt object is not properly initialized by the 
ckpt = tf.train.get_checkpoint_state(checkpoint_dir) line
Did you ensure that the files resulted from the fruit_train_net.py script are all in the folder pointed by the "checkpoint_dir" variable?

**Comment by sainisanjay** [comment]
Yes i can see in the fruit_models folder which is created during training. The following 5 files available 
/fruit_models/checkpoint   (381 bytes)
/fruit_models/graph.pbtxt  (284.3 kb)
/fruit_models/model.ckpt.data-00000-of-00001 (83.7 MB)
/fruit_models/model.ckpt.index  (1.5 kb)
/fruit_models/model.ckpt.meta  (145.2 kb)

**Comment by Horea94** [comment]
What is the value of the "checkpoint_dir" variable when it executes
ckpt = tf.train.get_checkpoint_state(checkpoint_dir) ?
Is it the same as the path to the folder with those 5 files?

**Comment by sainisanjay** [comment]
Yes its has same.

**Comment by sainisanjay** [comment]
I have resolved that issues but accuracy is coming always coming 0
```
Predicted 86 out of 100; partial accuracy 0.0000
Predicted 181 out of 200; partial accuracy 0.0000
Predicted 277 out of 300; partial accuracy 0.0000
Predicted 367 out of 400; partial accuracy 0.0000
Predicted 465 out of 500; partial accuracy 0.0000
Predicted 560 out of 600; partial accuracy 0.0000
Predicted 648 out of 700; partial accuracy 0.0000
```

**Comment by Horea94** [comment]
From the prints it looks like it counts the number of correctly classified images as well as the total number of images.
I think the issue is caused by python rounding down the result. Please try changing in the print the "correct / (total_test_images - images_left_to_process)" into 
"float(correct / (total_test_images - images_left_to_process))"

**Comment by sainisanjay** [comment]
I guess you are right but still showing same accuracy 0.0000. No luck
```
Predicted 11437 out of 12300; partial accuracy 0.0000
Predicted 11531 out of 12400; partial accuracy 0.0000
Predicted 11618 out of 12500; partial accuracy 0.0000
0
```

**Comment by Horea94** [comment]
I think I was mistaken. Please try
float(correct) / float(total_test_images - images_left_to_process)
to let python know that you want a division between 2 floats, and the result is expected to be a float.
What version of python are you using, because I cannot replicate this issue with my version? 
I use Python 3.6.6.

**Comment by Horea94** [comment]
For this script you need to provide the path to a jpg file, not the folder.
Something like 
`.../Fruit-Images-Dataset/src/image_classification$python fruit_detection/detect_fruits.py --image_path=/home/sanjay.saini/Deeplearning/DeepTensorFlow/My_TensorFlow_tutorials/Fruits_Classification/Fruit-Images-Dataset/test-multiple_fruits/apple.jpg`

**Comment by sainisanjay** [comment]
Thanks a lot.
