### ISSUE TITLE
Filename typo

### ISSUE THREAD

**Issue by MiltenPlescott** [Horea94/Fruit-Images-Dataset#9]
If I'm not mistaken, [Training/Pineapple Mini/137_100.jpg](https://github.com/Horea94/Fruit-Images-Dataset/blob/master/Training/Pineapple%20Mini/137_100.jpg) should be renamed to "r_137_100.jpg" to follow the naming format.

**Comment by Horea94** [comment]
Yes, you are correct. We renamed the file appropriately.
Thank you.
